const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
};

const ALLOWED_SORT_FIELDS = ['id', 'title', 'completed', 'createdAt'];
const ALLOWED_SORT_ORDERS = ['asc', 'desc'];

module.exports = {
  HTTP_STATUS,
  DEFAULT_PAGINATION,
  ALLOWED_SORT_FIELDS,
  ALLOWED_SORT_ORDERS,
};
